use DW_URG;
use BD_URG;

SET SQL_SAFE_UPDATES = 0;
DELETE FROM DW_URG.FACTOS;
DELETE FROM DW_URG.CAUSA;
DELETE FROM DW_URG.DATA;
DELETE FROM DW_URG.ESPECIALIDADE;
DELETE FROM DW_URG.PROVENIENCIA;
DELETE FROM DW_URG.PACIENTE;
DELETE FROM DW_URG.LOCAL;


INSERT IGNORE INTO DW_URG.CAUSA(desc_causa)
	SELECT DISTINCT DES_CAUSA FROM urg_inform_geral;

INSERT IGNORE INTO DW_URG.ESPECIALIDADE(desc_especialidade)
	SELECT DISTINCT ALTA_DES_ESPECIALIDADE FROM urg_inform_geral;

INSERT IGNORE INTO DW_URG.PACIENTE(sexo,data_nascimento)
	SELECT DISTINCT SEXO, DTA_NASCIMENTO FROM urg_inform_geral;

INSERT IGNORE INTO DW_URG.PROVENIENCIA(desc_proveniencia)
	SELECT DISTINCT DES_PROVENIENCIA FROM urg_inform_geral;

INSERT INTO DW_URG.DATA(ADMISSAO,ALTA)
	SELECT DISTINCT DATAHORA_ADM, DATAHORA_ALTA FROM urg_inform_geral;

INSERT IGNORE INTO DW_URG.LOCAL(desc_local)
	SELECT DISTINCT DES_LOCAL FROM urg_inform_geral;

select * from DW_URG.LOCAL;

-- INSERT INTO DW_URG.FACTOS(URG_EPISODIO,PROVENIENCIA_ID_PROVENIENCIA,ESPECIALIDADE_ID_ESPECIALIDADE,PACIENTE_ID_PACIENTE,CAUSA_ID_CAUSA,DATA_ID_DATA)
-- como juntar isto em varias tabelas???
/*
SELECT COUNT(DISTINCT URG_EPISODIO) FROM urg_inform_geral;
SELECT COUNT(DISTINCT DW_URG.PROVENIENCIA.ID_PROVENIENCIA) FROM DW_URG.PROVENIENCIA,urg_inform_geral WHERE DW_URG.PROVENIENCIA.desc_proveniencia = urg_inform_geral.DES_PROVENIENCIA;
SELECT COUNT(DISTINCT DW_URG.CAUSA.ID_CAUSA) FROM DW_URG.CAUSA,urg_inform_geral WHERE DW_URG.CAUSA.desc_causa = urg_inform_geral.DES_CAUSA;
SELECT COUNT(DISTINCT DW_URG.DATA.ID_DATA) FROM DW_URG.DATA,urg_inform_geral WHERE DW_URG.DATA.ADMISSAO = urg_inform_geral.DATAHORA_ADM AND DW_URG.DATA.ALTA = urg_inform_geral.DATAHORA_ALTA;
SELECT COUNT(DISTINCT DW_URG.ESPECIALIDADE.ID_ESPECIALIDADE) FROM DW_URG.ESPECIALIDADE,urg_inform_geral WHERE DW_URG.ESPECIALIDADE.desc_especialidade = urg_inform_geral.ALTA_DES_ESPECIALIDADE AND DW_URG.ESPECIALIDADE.desc_local = urg_inform_geral.DES_LOCAL;
SELECT COUNT(DISTINCT DW_URG.PACIENTE.ID_PACIENTE) FROM DW_URG.PACIENTE,urg_inform_geral WHERE DW_URG.PACIENTE.sexo = urg_inform_geral.SEXO AND DW_URG.PACIENTE.data_nascimento = urg_inform_geral.DTA_NASCIMENTO;
*/

INSERT INTO DW_URG.FACTOS(URG_EPISODIO,PROVENIENCIA_ID_PROVENIENCIA,ESPECIALIDADE_ID_ESPECIALIDADE,PACIENTE_ID_PACIENTE,CAUSA_ID_CAUSA,DATA_ID_DATA,LOCAL_ID_LOCAL)
SELECT raw.URG_EPISODIO,pr.ID_PROVENIENCIA , e.ID_ESPECIALIDADE, pa.ID_PACIENTE, c.ID_CAUSA, d.ID_DATA, l.ID_LOCAL
FROM BD_URG.urg_inform_geral raw
INNER JOIN DW_URG.CAUSA c on raw.DES_CAUSA=c.desc_causa
INNER JOIN DW_URG.DATA d on (raw.DATAHORA_ADM=d.ADMISSAO and raw.DATAHORA_ALTA=d.ALTA )
INNER JOIN DW_URG.ESPECIALIDADE e  on raw.ALTA_DES_ESPECIALIDADE=e.desc_especialidade 
INNER JOIN DW_URG.PACIENTE pa on (raw.SEXO=pa.sexo and raw.DTA_NASCIMENTO=pa.data_nascimento)
INNER JOIN DW_URG.PROVENIENCIA pr on raw.DES_PROVENIENCIA =pr.desc_proveniencia
INNER JOIN DW_URG.LOCAL l on raw.DES_LOCAL=l.desc_local;

SELECT URG_EPISODIO, d.ADMISSAO, d.ALTA, e.desc_especialidade, l.desc_local, pr.desc_proveniencia, pa.sexo, pa.data_nascimento , 
c.desc_causa 
FROM DW_URG.FACTOS raw
INNER JOIN DW_URG.CAUSA c on raw.CAUSA_ID_CAUSA=c.ID_CAUSA
INNER JOIN DW_URG.DATA d on raw.DATA_ID_DATA=d.ID_DATA
INNER JOIN DW_URG.ESPECIALIDADE e on raw.ESPECIALIDADE_ID_ESPECIALIDADE=e.ID_ESPECIALIDADE
INNER JOIN DW_URG.LOCAL l on raw.LOCAL_ID_LOCAL=l.ID_LOCAL
INNER JOIN DW_URG.PACIENTE pa on raw.PACIENTE_ID_PACIENTE=pa.ID_PACIENTE
INNER JOIN DW_URG.PROVENIENCIA pr on raw.PROVENIENCIA_ID_PROVENIENCIA =pr.ID_PROVENIENCIA;
